### PR TITLE
Cleanup after OSX support

### PR DESCRIPTION
**Pull request by br101**
Hi, I did a little cleanup. Please check if this still works for you...

And next time please follow my coding style (intent with TAB, no braces). It is basically Linux kernel style: https://www.kernel.org/doc/Documentation/CodingStyle. I don't mind what you do in ifctrl-osx.m but the reset should be consistent.

Thanks!

### CODE REVIEW

**Comment by br101** [comment]
What if we rename ifctrl-osx.m to ifctrl-osx.c … ? I'm sorry I asked you before to name it .m but it seems simpler if it's just a .c file as well...

**Comment by fuji246** [comment]
rename to .c doesn't work

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:10:1: error: 

```
  expected identifier or '('
```

@class NSInvocation, NSMethodSignature, NSCoder, NSString, NSEnumerator;

^

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:11:1: error: 

```
  expected identifier or '('
```

@class Protocol;

^

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:17:1: error: 

```
  expected identifier or '('
```

@protocol NSCopying

^

fatal error: too many errors emitted, stopping now [-ferror-limit=]

20 errors generated.

make: **\* [ifctrl-osx.o] Error 1

**Comment by br101** [comment]
Oh. Sorry I broke everything. I reverted most of my changes. Please check again. Sorry

**Comment by fuji246** [comment]
Works now, thanks!

**Comment by br101** [comment]
Thanks to you :-)

**Pull request closed without merging**
